global using Android.Webkit;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.Platform;
global using Avalonia.Data;
global using Avalonia.Platform;
global using System.ComponentModel;
global using Android.Content; 
global using AndroidWebView = Android.Webkit.WebView;
global using AndroidApplication = Android.App.Application;
global using AndroidUri = Android.Net.Uri;
global using AndroidWebResourceResponse = Android.Webkit.WebResourceResponse;
global using AndroidColor = Android.Graphics.Color;
global using JavaFile = Java.IO.File;
global using System.Runtime.InteropServices; 
global using Avalonia.WebView.Shared.Handlers;
global using WebView.Core.Configurations;
global using WebView.Core;
global using Avalonia.WebView.Shared;
global using Android.OS;
global using Android.Views;
global using Avalonia.Platform.Storage;
global using Avalonia.WebView.Android.Handlers;
global using WebView.Core.Extensions;
global using Avalonia.WebView.Android.Core;
global using Android.Runtime;
global using System.Runtime.Versioning;
global using WebView.Core.Models;
global using Avalonia.WebView.Android.Clients;

global using static Android.Views.ViewGroup;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.Primitives;
global using System.Buffers;
global using System.Collections;

global using Avalonia.WebView.Android.Helpers;
global using Avalonia.WebView.Shared.Interfaces;
global using WebView.Core.Events;
global using WebView.Core.Helpers;
global using Avalonia.WebView.Android.Common;
global using System.Reflection;

global using DryIoc.Shared.Extensions;
global using WebView.Core.Ioc;
global using WebView.Core.Enums;