global using MacosWebView = WebKit.WebView;
global using WebKit; 
global using Foundation;
global using System.ComponentModel;
global using Avalonia.Data;
global using Avalonia.Platform;
global using AppKit;
global using Avalonia.WebView.Shared.Handlers; 
global using WebView.Core; 
global using Avalonia.Controls; 
global using System.Runtime.InteropServices;
global using WebView.Core.Configurations;
global using Avalonia.WebView.Shared;
global using System.Threading;
global using System;
global using Avalonia.Input; 
global using System.Drawing;
global using WebView.Core.Events;
global using WebView.Core.Models;
global using Microsoft.Extensions.FileProviders;
global using System.Reflection;
global using DryIoc.Shared.Extensions;
global using WebView.Core.Ioc;
global using System.IO;
global using System.Linq;
using Avalonia.WebView.Shared.Interfaces;